if ispc
    mex -O ...
        -I"C:\Program Files\ZeroMQ 4.0.3\include" ...
        -L"C:\Program Files\ZeroMQ 4.0.3\lib" ...
        -llibzmq-v120-mt-4_0_3 ...
        *.cc
elseif isunix
    mex -O ...
        -I"/usr/include" ...
        -L"/usr/lib/x86_64-linux-gnu" ...
        -lzmq ...
        *.cc
else
end
